services:
  - type: web
    name: urbnctrl-admin
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: REACT_APP_API_URL
        value: https://urbnctrl-backend.onrender.com/api 